language: crystal
crystal:
  - latest
env:
  - TRAVIS_POSTGRESQL_VERSION=9.6
  - TRAVIS_POSTGRESQL_VERSION=9.5
  - TRAVIS_POSTGRESQL_VERSION=9.4
  - TRAVIS_POSTGRESQL_VERSION=9.3
  - TRAVIS_POSTGRESQL_VERSION=9.2
before_install:
  - mysql -uroot -e "create database topaz_test"
  - sudo apt-get install python-software-properties
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3 
  - sudo sqlite3 -version
  - sudo service postgresql stop
  - sudo service postgresql start $TRAVIS_POSTGRESQL_VERSION
  - createuser root
  - createdb topaz_test
  - export DATABASE_URL=postgres://root@localhost/topaz_test
script: make
